### PR TITLE
[lab-bash-master] Miguel González

### PR DESCRIPTION
**Pull request by G0nka**

### CODE REVIEW

**Comment by ta-data-mad** [comment]
Hello Miguel,

Your solution.txt file is empty. Did you have any issues uploading it?

**Comment by G0nka** [comment]
Hi there,
I thought there was nothing to send for this lab.

But now I am realizing you probably mean this part, right?
Well I missed it. But I can do it now if needed.

Best,

Miguel González

[image: image.png]

**Comment by ta-data-mad** [comment]
Hey man!. The solution.txt file is still empty. Did you upload it? Maybe you did it somewhere else?

**Comment by ta-data-mad** [comment]
I thought you uploaded something because the last commit says "lab-finished"

**Comment by ta-data-mad** [comment]
Solution.txt file is empty

**Pull request closed without merging**
