### PR TITLE
[lab-bash-master] Marina Fernández

### PR DESCRIPTION
**Pull request by marinafdezban**

### CODE REVIEW

**Comment by ta-data-mad** [comment]
Hello Marina, 

I don't see your solution.txt file. Did you have any issues uploading it?

**Comment by marinafdezban** [comment]
Hi, 

I thought it was well uploaded, I don't know what could have happened.

After today's class, I will look it up and tried again.

Sorry :'(

**Comment by ta-data-mad** [comment]
Hello Marina, did you upload the file? :)

**Comment by ta-data-mad** [comment]
solution.txt file missing

**Pull request closed without merging**
